package memory

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/ximilala/viking-go/internal/memory/mergeop"
)

// GenerateGoStructs reads all YAML schemas from dir and generates Go structs
// into the given output file. The generated file will belong to the specified package.
func GenerateGoStructs(schemaDir, outputPath, pkgName string) error {
	reg := NewMemoryTypeRegistry()
	if err := reg.LoadFromDir(schemaDir); err != nil {
		return fmt.Errorf("load schemas: %w", err)
	}

	schemas := reg.All()
	if len(schemas) == 0 {
		return fmt.Errorf("no enabled schemas found in %s", schemaDir)
	}

	type structDef struct {
		TypeName    string
		Description string
		Fields      []fieldDef
	}
	type fieldDef_ = fieldDef

	var defs []structDef
	for _, s := range schemas {
		sd := structDef{
			TypeName:    toPascalCase(s.MemoryType),
			Description: s.Description,
		}
		for _, f := range s.Fields {
			sd.Fields = append(sd.Fields, fieldDef{
				GoName:      toPascalCase(f.Name),
				GoType:      fieldTypeToGo(f.FieldType),
				JSONTag:     f.Name,
				Description: f.Description,
			})
		}
		defs = append(defs, sd)
	}

	if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	f, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("create output file: %w", err)
	}
	defer f.Close()

	data := map[string]any{
		"Package": pkgName,
		"Structs": defs,
	}

	return structTemplate.Execute(f, data)
}

type fieldDef struct {
	GoName      string
	GoType      string
	JSONTag     string
	Description string
}

func fieldTypeToGo(ft mergeop.FieldType) string {
	switch ft {
	case mergeop.FieldString:
		return "string"
	case mergeop.FieldInt64:
		return "int64"
	case mergeop.FieldFloat32:
		return "float32"
	case mergeop.FieldBool:
		return "bool"
	default:
		s := string(ft)
		switch {
		case strings.HasPrefix(s, "list"):
			return "[]string"
		case strings.HasPrefix(s, "dict"), strings.HasPrefix(s, "map"):
			return "map[string]any"
		case s == "datetime" || s == "date":
			return "string"
		case s == "int":
			return "int"
		case s == "float" || s == "float64":
			return "float64"
		default:
			return "any"
		}
	}
}

func toPascalCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-' || r == '.'
	})
	var b strings.Builder
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		if len(p) > 1 {
			b.WriteString(p[1:])
		}
	}
	return b.String()
}

var structTemplate = template.Must(template.New("structs").Parse(`// Code generated by viking-go schema generator. DO NOT EDIT.
package {{ .Package }}
{{ range .Structs }}
// {{ .TypeName }} — {{ .Description }}
type {{ .TypeName }} struct {
{{- range .Fields }}
	{{ .GoName }} {{ .GoType }} ` + "`" + `json:"{{ .JSONTag }}"` + "`" + ` // {{ .Description }}
{{- end }}
}
{{ end }}
`))
